apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1app1nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1app1nginx
  template:
    metadata:
      labels:
        app: app1app1nginx 
    spec:
      containers:
        - name: app1app1nginx 
          image: rnaksdevopsacr.azurecr.io/app1app1nginx
          ports:
          - containerPort: 80