trigger:
- master

variables:
  image_name: custom2aksnginxapp1
  image_tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'manual-rnaksdevopsacr-svc'
          repository: '$(image_name)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(image_tag)
            $(Build.SourceVersion)
      - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)
      - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@1
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      - bash: echo After copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-manifests'
          publishLocation: 'Container'

    - job: TrivyScanContainerImage
      displayName: Scan container image by Trivy
      steps:
      - task: Docker@2
        displayName: 'Build an image'
        inputs:
          command: build
          repository: $(image_name)
          tags: $(image_tag)
          dockerFile: '**/Dockerfile'
      - script: |
          mkdir report
          trivy image -s HIGH,CRITICAL $(image_name):$(image_tag) | tee ./report/trivy-image-scan-report.txt
        displayName: "Image scan by Trivy"
        continueOnError: true
      - task: CopyFiles@1
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/report/trivy-image-scan-report.txt'
          ArtifactName: 'trivy-scan'
          publishLocation: 'Container'
